name: boardly-prod
services:
  web:
    image: boardly-client:prod
    build:
      context: .
      target: prod
      dockerfile: ./apps/client/Dockerfile
    ports:
      - "5173:80"
  server:
    image: boardly-server:prod
    build:
      context: .
      target: prod
      dockerfile: ./apps/server/Dockerfile
    ports:
      - "5000:5000"
