name: boardly-dev
services:
  web:
    image: boardly-client:dev
    build:
      context: .
      target: dev
      dockerfile: ./apps/client/Dockerfile
    ports:
      - "5173:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./apps/client:/app/apps/client
    develop:
      watch:
        - action: rebuild
          path: ./apps/client/package.json
          target: package.json
        - action: rebuild
          path: ./apps/client/package-lock.json
          target: package-lock.json
  server:
    image: boardly-server:dev
    build:
      context: .
      target: dev
      dockerfile: ./apps/server/Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./apps/server:/app/apps/server
    develop:
      watch:
        - action: rebuild
          path: ./apps/server/package.json
          target: package.json
        - action: rebuild
          path: ./apps/server/package-lock.json
          target: package-lock.json
