name: boardly-dev
services:
  web:
    image: boardly-client:dev
    build:
      context: ./apps/client
      target: dev
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./apps/client:/app/apps/client
      - /app/apps/client/node_modules
