name: boardly-dev
services:
  web:
    image: boardly-client:dev
    build:
      context: .
      target: dev
      dockerfile: ./apps/client/Dockerfile
    ports:
      - "5173:5173"
    env_file:
      - .env.client
    volumes:
      - ./apps/client:/app/apps/client
      - ./packages:/app/packages
    develop:
      watch:
        - action: rebuild
          path: ./apps/client/package.json
          target: package.json
        - action: rebuild
          path: ./apps/client/package-lock.json
          target: package-lock.json
        - action: rebuild
          path: ./packages/shared/package.json
          target: package.json
        - action: rebuild
          path: ./packages/shared/package-lock.json
          target: package-lock.json
    depends_on:
      - server
  server:
    image: boardly-server:dev
    build:
      context: .
      target: dev
      dockerfile: ./apps/server/Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./apps/server:/app/apps/server
      - ./packages:/app/packages
    env_file:
      - .env.server
    develop:
      watch:
        - action: rebuild
          path: ./apps/server/package.json
          target: package.json
        - action: rebuild
          path: ./apps/server/package-lock.json
          target: package-lock.json
        - action: sync+restart
          path: ./apps/server/src/prisma/schema.prisma
          target: schema.prisma
        - action: sync+restart
          path: ./apps/server/src/prisma.config.ts
          target: prisma.config.ts
        - action: rebuild
          path: ./packages/shared/package.json
          target: package.json
        - action: rebuild
          path: ./packages/shared/package-lock.json
          target: package-lock.json
    depends_on:
      - db
  db:
    image: postgres:15
    ports:
      - "5432:5432"
    restart: always
    env_file:
      - .env.db
    volumes:
      - boardly-data:/var/lib/postgresql/data

volumes:
  boardly-data:
